create table prices (id bigint generated by default as identity, 
                     brand_id bigint, 
                     curr varchar(255), 
                     end_date timestamp(6) with time zone, 
                     price float(53), 
                     price_list bigint, 
                     priority bigint, 
                     product_id integer, 
                     start_date timestamp(6) with time zone, 
                     primary key (id));
                     
INSERT INTO prices (brand_id, curr, end_date, price, price_list, priority, product_id, start_date)
VALUES
   (1, 'EUR', '2020-12-31 23:59:59.000000', 35.50, 1, 0, 35455, '2020-06-14 00:00:00.000000'),
   (1, 'EUR', '2020-06-14 18:30:00.000000', 25.45, 2, 1, 35455, '2020-06-14 15:00:00.000000'),
   (1, 'EUR', '2020-06-15 11:00:00.000000', 30.50, 3, 1, 35455, '2020-06-15 00:00:00.000000'),
   (1, 'EUR', '2020-12-31 23:59:59.000000', 38.95, 4, 1, 35455, '2020-06-15 16:00:00.000000');
   
commit;
